Show remote carets
RationalCoding/multihack-brackets pull request #23
Opened 2017-04-29 16:42 UTC by Worie

Here we go. I tried to follow your codestyle, I guess it should be ok. The changes provided should cover every input from peers (multiple carets, removals, additions, pastes and cuts)

If this PRs alright, then in the future I guess we should create a html template for carets (for future features such as displaying the caret owners name and for code maintenance purposes)

2017-04-29 17:12 UTC, Worie commented
Just realized that it works well when there are only two peers, but fails with more then that.

The problem is that upon recieving the change event, the `remoteCarets` set is being cleared.

So in scenario: 

1. Peer A connects
2. Peer B connects
3. Peer C connects
4. Peer B moves his caret
5. Peer A and C sees it
6. Peer C moves his caret.
7. Peer A loses the state of peer B caret.

So, each peer should have probably his own `Set()`.

2017-04-29 19:13 UTC, RationalCoding commented on main.js
> +      newEditor._codeMirror.on('changes', onCodeChanges)
If we are going to start listening to operation-batched changes, we should only use the 'changes' event.

2017-04-29 19:14 UTC, RationalCoding commented on main.js
> +  function sendLocalCaretsMoves (cm, change) {
Do you mind adding a few comments to this to explain how you are calculating the caret positions from the changes?

2017-04-29 19:15 UTC, Worie commented on main.js
> +  function sendLocalCaretsMoves (cm, change) {
Sure, I'll sit to it when finish your review :)

2017-04-29 19:17 UTC, RationalCoding commented on main.js
> +    if (fromWebPath(data.filePath) !== documentRelativePath) return
Fine for now, but add a TODO so we can support tracking carets in closed files. (Needs to be done for selections to if I remember correctly.)

2017-04-29 19:20 UTC, RationalCoding commented
Looks good, thanks for figuring this out. I added a few comments.

I won't be able to merge this PR because I did a LOT of refactoring for the YJS integration, but I will include your changes in the next major release. I'll open up a PR when I do so you can review.

2017-04-29 19:23 UTC, RationalCoding commented on main.js
> +  var remoteCarets = new Set()
I don't use ES6 anywhere else. Please use an object set and use keys to iterate.

2017-04-29 19:24 UTC, t-mullen requested changes
Changed my mind. YJS integration will take too long.

Please make the requested style changes and I'll run some tests.

2017-04-29 19:49 UTC, Worie commented
Guess that's it. Besides the requested changes I've left a comment about the issue I mentioned in https://github.com/RationalCoding/multihack-brackets/pull/23#issuecomment-298181615 earlier.

2017-04-29 22:52 UTC, RationalCoding commented
OK, seems to be working great aside from the issue with >2 users. I'll fix that in a later commit when I do cursor colours. Thanks @Worie !

Would you like to be added as a maintainer? I can always use some more help developing this :)

2017-04-29 22:52 UTC, merged

2017-04-30 07:18 UTC, Worie commented
I'm glad it's ok :) When it comes to me as a maintainer - I can't really promise anything as I don't know how much spare time will I have, but sure - that'd be nice, thanks!